### ISSUE TITLE
Inflation endpoint in LCD not working

### ISSUE THREAD

**Issue by CrackLord** [echelonfoundation/echelon#42]
## Summary of Bug

The inflation endpoint is not working, but it is documented on the swagger documentation.

## Steps to Reproduce

`curl -X GET "https://lcd-echelon.whispernode.com/cosmos/mint/v1beta1/inflation" -H "accept: application/json"`
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by echelonfoundation** [comment]
We can update the documentation, or please provide a PR.

**Resolution:**

The inflation rate endpoint is: `/echelon/inflation/v1/inflation_rate`

`curl -X GET "https://lcd-echelon.whispernode.com/echelon/inflation/v1/inflation_rate" -H "accept: application/json"`
